name: Check update

on: [push]

jobs:
  publish:
    name: check this week in rust and post to telegram
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create dir
        shell: bash
        run: touch ./.env && touch /home/runner/work/this_week_in_rust.rs/this_week_in_rust.rs/this_week_in_rust.last_id

      - name: get latest last-id
        uses: sergeysova/gist-read-action@master
        id: last-id
        with:
          gist_id: 9132dba40f4c806617043287a9f5d1e5
          file_name: this_week_in_rust.last_id
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: echo "${{ steps.last-id.outputs.content }}" > /home/runner/work/this_week_in_rust.rs/this_week_in_rust.rs/this_week_in_rust.last_id

      - run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://docker.pkg.github.com -u ${{ github.actor }} --password-stdin && \
          docker pull docker.pkg.github.com/sergeysova/this_week_in_rust.rs/main

      - name: post to this week in rust
        if: always()
        uses: ./
        with:
          bot-token: ${{ secrets.BOT_TOKEN }}
          chat-id: ${{ secrets.CHAT_ID }}
          config-dir: /github/workspace/

      - name: save updated last-id
        uses: actions/upload-artifact@v1
        with:
          name: last-id
          path: /home/runner/work/this_week_in_rust.rs/this_week_in_rust.rs/this_week_in_rust.last_id
