name: Check update

on: [push]

jobs:
  publish:
    name: check this week in rust and post to telegram
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create dir
        shell: bash
        run: touch /tmp/this_week_in_rust.last_id
      # - name: get latest last-id
      #   uses: actions/download-artifact@v1
      #   with:
      #     name: last-id
      # - if: failure()
      #   shell: bash
      #   run: echo ""

      - run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://docker.pkg.github.com -u ${{ github.actor }} --password-stdin && \
          docker pull docker.pkg.github.com/sergeysova/this_week_in_rust.rs/main

      - name: post to this week in rust
        if: always()
        uses: ./
        with:
          bot-token: ${{ secrets.BOT_TOKEN }}
          chat-id: ${{ secrets.CHAT_ID }}
          config-dir: /tmp

      - name: save updated last-id
        uses: actions/upload-artifact@v1
        with:
          name: last-id
          path: /tmp/this_week_in_rust.last_id
